import 'package:any_percent_training_tracker/models/exercise_model.dart';
List<Exercise> seedExercises = [
  Exercise(
    name: "Barbell Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Dumbbell Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Incline Barbell Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Incline Dumbbell Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Decline Barbell Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Decline Dumbbell Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Close Grip Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Swiss Bar Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Dumbbell Flyes",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Cable Chest Press",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Cable Flyes",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Chest",
  ),
  Exercise(
    name: "Dips",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Chest",
    
  ),
  Exercise(
    name: "Conventional Deadlift",
    type: "Compound",
    movementType: "Hinge",
    bodyPart: "Back",
  ),
  Exercise(
    name: "Sumo Deadlift",
    type: "Compound",
    movementType: "Hinge",
    bodyPart: "Back",
  ),
  Exercise(
    name: "Romanian Deadlift",
    type: "Compound",
    movementType: "Hinge",
    bodyPart: "Back",
  ),
  Exercise(
    name: "Bent-Over Barbell Rows",
    type: "Compound",
    movementType: "Pull",
    bodyPart: "Back",
  ),
  Exercise(
    name: "T-Bar Rows",
    type: "Compound",
    movementType: "Pull",
    bodyPart: "Back",
  ),
  Exercise(
    name: "Seated Cable Rows",
    type: "Compound",
    movementType: "Pull",
    bodyPart: "Back",
  ),
  Exercise(
    name: "Wide Grip Pull-Ups",
    type: "Compound",
    movementType: "Pull",
    bodyPart: "Back",
  ),
  Exercise(
    name: "Close Grip Pull-Ups",
    type: "Compound",
    movementType: "Pull",
    bodyPart: "Back",
  ),
  Exercise(
    name: "Overhead Press Exercise(Barbell)",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Dumbbell Overhead Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Arnold Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Barbell Shrugs",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Dumbbell Lateral Raises",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Front Dumbbell Raises",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Rear Delt Flyes",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Upright Rows",
    type: "Compound",
    movementType: "Pull",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Face Pulls",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Shoulders",
  ),
  Exercise(
    name: "Low Bar Back Squats",
    type: "Compound",
    movementType: "Squat",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "High Bar Back Squats",
    type: "Compound",
    movementType: "Squat",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Front Squats",
    type: "Compound",
    movementType: "Squat",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Bulgarian Split Squats",
    type: "Compound",
    movementType: "Lunge",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Lunges",
    type: "Compound",
    movementType: "Lunge",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Leg Press",
    type: "Compound",
    movementType: "Squat",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Hack Squats",
    type: "Compound",
    movementType: "Squat",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Leg Extensions",
    type: "Isolation",
    movementType: "Squat",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Hamstring Curls",
    type: "Isolation",
    movementType: "Hinge",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Glute Bridges",
    type: "Compound",
    movementType: "Hinge",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Calf Raises",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Lower Body",
  ),
  Exercise(
    name: "Barbell Bicep Curls",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Dumbbell Bicep Curls",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Hammer Curls",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Preacher Curls",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Concentration Curls",
    type: "Isolation",
    movementType: "Pull",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Skull Crushers",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Close Grip Bench Press",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Tricep Dips",
    type: "Compound",
    movementType: "Push",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Tricep Pushdowns",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Arms",
  ),
  Exercise(
    name: "Overhead Tricep Extensions",
    type: "Isolation",
    movementType: "Push",
    bodyPart: "Arms",
  )
];

final List<String> autoComplete = seedExercises.map((exercise) => exercise.name).toList();
